tool: more ifdefs for asymmetric auth feature
Yubico/yubihsm-shell pull request #126
Opened 2020-12-18 13:02 UTC by klali

get_device_pubkey is part of this feature

this is maybe not ideal, but starting to filter the commandline.ggo for a temporary ifdef feels over the top.

2020-12-18 13:49 UTC, a-dma commented
Agreed that it's not the nicest solution. I guess we could have to versions of cmdline.ggo and include one or the other when running cmake.

I'm also OK with this solution though.

2020-12-18 13:50 UTC, a-dma approved these changes

2020-12-18 19:49 UTC, qpernil commented
Kinda confirms my feeling this whole deal of removing this is over the top, but... As far as it goes it looks OK

2020-12-18 19:51 UTC, qpernil requested changes

2020-12-18 19:51 UTC, qpernil commented on src/main.c
> +          fprintf(stderr, "get-device-key not supported in this build.");
Should be get-device-pubkey

2020-12-21 10:43 UTC, qpernil approved these changes

2020-12-22 09:36 UTC, merged